#!/bin/bash

#* Global defaults
export EDITOR="vim"
export VISUAL="code"

#* Pyenv
export PYENV_ROOT="$HOME/.pyenv"

#* Path exports
export WORKSPACE_PATH="${HOME}/workspace"

#* nnn config
# Nord
BLK="0B" CHR="0B" DIR="04" EXE="06" REG="00" HARDLINK="06" SYMLINK="06" MISSING="00" ORPHAN="09" FIFO="06" SOCK="0B" OTHER="06"
# OneDark
# BLK="04" CHR="04" DIR="04" EXE="00" REG="00" HARDLINK="00" SYMLINK="06" MISSING="00" ORPHAN="01" FIFO="0F" SOCK="0F" OTHER="02"

export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG="f:finder;o:fzopen;p:preview-tui;d:diffs;t:nmount;v:imgview"
