#!/bin/bash

# Antlr
# export CLASSPATH=".:/usr/local/lib/antlr-4.8-complete.jar:$CLASSPATH"
# alias antlr4='java -jar /usr/local/lib/antlr-4.8-complete.jar'
# alias grun='java org.antlr.v4.gui.TestRig'

# Old terminnal colors
# export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
# export CLICOLOR=1
# export LSCOLORS=GxFxCxDxBxegedabagaced
